name: 'Docker'

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build:
    name: "Push Docker Image"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-lta-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-nucat-

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        # list of Docker images to use as base name for tags
        images: |
          icecube/nucat
        # add git short SHA as Docker tag
        flavor: |
            prefix=client-
        tags: |
            type=sha
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      if: ${{ github.event_name != 'pull_request' }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: client
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}

    - name: Docker meta
      id: docker_meta2
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        # list of Docker images to use as base name for tags
        images: |
          icecube/nucat
        # add git short SHA as Docker tag
        flavor: |
            prefix=server-
        tags: |
            type=sha
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

    - name: Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: server
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: ${{ steps.docker_meta2.outputs.tags }}
        labels: ${{ steps.docker_meta2.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
